### ISSUE TITLE
Harvesting doesn't work (1.18-1.19)

### ISSUE THREAD

**Issue by GermanArtur** [JamCoreModding/RightClickHarvest#10] opened 2022-06-08 08:08 UTC
Harvesting does not work with a right mouse click, despite the settings in the configuration. Version 2.0.0 is the last version in which this worked correctly.

**Comment by Dr01000111** [comment] 2022-06-08 19:08
> Try crouching and right clicking

Still doesn't work

**Comment by Jamalam360** [comment] 2022-06-08 19:10
Need you `config/rightclickharvest.json` and `logs/latest.log` then

**Comment by Jamalam360** [comment] 2022-06-14 15:30
@Dr01000111 I will need to close this issue if you can't give the requested information - it works in my testing.

**Comment by GermanArtur** [comment] 2022-06-15 11:01
config/rightclickharvest.json - https://pastebin.com/icQ8u3Ey
logs/latest.log - https://pastebin.com/DcZt7dyj

Bug is that I can't harvest by right-clicking when there is an item or block in the main hand.

**Comment by Jamalam360** [comment] 2022-06-15 11:18
> when there is an item or block in the main hand

That is not a bug, that's intended behaviour

**Comment by Fourmisain** [comment] 2022-06-15 15:22
Please add a config switch for that.
When harvesting different kinds of plants, your hotbar constantly gets filled with random crops/seeds, so you have to keep clearing your hotbar to use your hand, which is pretty annoying.
While you can hold seeds in your hand, it'll replace the crop you're harvesting with it, which is usually not what you want either (or this might be another mod, I'm not sure, I ran into this with a modpack).

---

On a completely different topic, I was just about to look at the code, figure out what has changed and maybe PR this config feature but noticed I couldn't find anything older than 27 days - I couldn't even find my old commits and thought I was at the wrong repo until I saw you rewrote the git history.

May I ask why you did that?

Not only is it really inconvenient to figuring out, well, the history, but you squashed my commits with it too - Github doesn't even think I'm a [contributor](https://github.com/JamCoreModding/RightClickHarvest/graphs/contributors) anymore.
It's a little disheartening to be honest.

At least my PRs still exist and I didn't delete my [fork](https://github.com/Fourmisain/RightClickHarvestFabric/tree/plusplus) either, so it's not like everything is suddenly gone.
But still, please consider others as well when doing something like this.

**Comment by Jamalam360** [comment] 2022-06-15 15:48
- Yeah I'll get adding a config option in a couple minutes.
- Sorry about that, that was done to remove some information from the git history that I didn't want easily available publicly. I didn't intend to remove your contributions - I do appreciate them.

**Closed** 2022-06-15 16:03 UTC

**Comment by Fourmisain** [comment] 2022-06-15 16:11
> Sorry about that, that was done to remove some information from the git history that I didn't want easily available publicly. I didn't intend to remove your contributions - I do appreciate them.

Ohh, in that case I'll stomp my fork too!

Note for the future:
You can rewrite specific commits by checking them out, ammending them and rebasing everything on top of the newly changed commit. It's also possible to delete/skip specific commits in the history by checking out the commit after it and squashing the last 2 commits (something like `git reset --soft HEAD~2`, `git commit` I think)

I often do that locally to keep the history clean when I do PRs - but let's just do it this way.

**Comment by Fourmisain** [comment] 2022-06-15 16:13
Ohhh, yeah, I think I get what happened now! :laughing:

**Comment by Jamalam360** [comment] 2022-06-15 16:14
Rookie git mistakes lol, this was my first mod O_o
